### ISSUE TITLE
Peer feedback van Hilal

### ISSUE THREAD

**Issue by Hilal-Tapan** [K3A101/stress-relief-quotes#1]
Repository
Scan your buddy's repository
Is there a repo description at the top?
- Ja

Is there a link to the live web app provided with GitHub Pages?
- Ja 

Is the repo open to issues?
- Ja

Does it include a gitignore
- Ja 

Is the concept described well in the readme?
- Ja heel erg goed. Alles is super uitgebreid en duidelijk beschreven inclusief foto's. Heel netjes!

Is the API described in the readme?
- NIet in de readme maar wel in de wiki. Hier is die super uitgebreid geschreven hoe ze zelf een api heeft gemaakt en hoe het werkt.

Code
Ik vind het netjes dat de javascript op nette volgorde staat. Dus eerst de variabelen, daarna de logica en daarna de functies. Onderop heb je de wat comments van stukken code. Ziet er goed uit. Ik vind de variabelen duidelijke namen hebben en begrijpbaar. Wat handig kan zijn is om bij elke functie in comments te zetten wat het doet zodat dit voor iedereen gelijk duidelijk is.

Als best practises heeft ze nette waterfall methodes toegepast. 

De css ziet er goed uit, er is fijn onderscheid gemaakt tussen header, main etc. Html is ook netjes en goed te volgen.

Bij je wiki doen je img's het alleen niet dus deze heb ik niet kunnen bekijken. Maar de img die het wel deed in je readme van het ontwerp van je site is heel netjes.

**Comment by K3A101** [comment]
# Mogelijke oplossingen
- Als oplossing ga ik de gecommenteerde codes bij javascript bestand weghalen. Zodat  het verzorgd blijft. 
- Verder ga ik comments toevoegen bij de functies zodat het makkelijk te begrijpen is.
-  Ten slotte ga ik de afbeeldingen in mijn wiki updaten.
