### ISSUE TITLE
js document queryselector

### ISSUE THREAD

**Issue by laibaaac** [K3A101/stress-relief-quotes#3]
Misschien kan je als doc queryselector een $ teken gebruiken, heb je niet zo lange regels en hoef je het niet steeds weer uit te typen, bespaart je veel moeite!!! (ps kijk naar de voorbeeld code van joost)

**Comment by laibaaac** [comment]
Ik zie al dat je de voorbeeld in comments hebt staan, neem het over!

**Comment by K3A101** [comment]
Goeie tip, maar als ik die dollar teken zou toepassen, dan wordt de code niet begrijpbaar meer voor mij.  Ik ben nog steeds een newbie met javascript dus hoe uitgebreider de code, hoe beter voor mij.
