### ISSUE TITLE
Code opschonen

### ISSUE THREAD

**Issue by laibaaac** [K3A101/stress-relief-quotes#4]
probeer je code schoon te houden, aan het einde van je js file zijn er veel comments.

**Comment by laibaaac** [comment]
misschien beautify of prettier als extension gebruiken in vs code, heel handig!!!

**Comment by K3A101** [comment]
Yes, ik heb de de comments weggehaald, want ze staan wel in oude versie. Beautify is onbeschikbaar geworden omdat het wordt niet meer ondersteund, dus ik ga even kijken hoe prettier werkt.
